version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/semantics
    ports:
      - "4000:4000"
    depends_on:
      - db
