---

- name: Add official postgresql repository key
  become: yes
  apt_key:
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    state: present

- name: Add official postgresql repository
  become: yes
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main 9.5'
    state: present
    update_cache: yes

- name: Install prerequisites
  become: yes
  apt:
    pkg: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
    - postgresql-client
    - postgresql-contrib
    - python-pycurl
    - python-psycopg2 # https://github.com/ansible/ansible/issues/6989
    - libpq-dev # For building ruby 'pg' gem

- name: PostgreSQL user
  postgresql_user:
    name: semantics
    password: semantics123
    encrypted: no
    state: present
    login_user: postgres
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: PostgreSQL databases
  postgresql_db:
    name: semantics_development
    owner: semantics
    encoding: UTF8
    template: template0
    state: present
    login_user: postgres
  become: yes
  become_user: postgres
