default: &default
  adapter: postgresql
  encoding: unicode
  username: semantics
  password: semantics123
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: semantics_development

test:
  <<: *default
  database: semantics_test

#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  url: <%= $DATABASE_URL %>